[package]
name = "naia-client"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Provides a cross-platform client that can send/receive messages to/from a server, and has a pool of in-scope entities/components that is synced with the server."
documentation = "https://docs.rs/naia-client"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]
wbindgen = [ "naia-client-socket/wbindgen", "naia-shared/wbindgen" ]
mquad = [ "naia-client-socket/mquad", "naia-shared/mquad" ]
bevy-support = ["naia-shared/bevy-support"]

[dependencies]
naia-client-socket = { version = "=0.7.1" }
naia-shared = { version = "=0.7.0", path = "../shared" }
cfg-if = "0.1.10"
log = "0.4"
byteorder = "1.3"
