[package]
name = "naia-bevy-client-demo"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

native = []

[dependencies]
naia-bevy-client = { path = "../../../adapters/bevy/client" }
naia-bevy-demo-shared = { path = "../shared" }
bevy = { version="0.6.0", default-features=false }
winit = { version = "0.26" }
rand = { version = "0.7" }
getrandom = { version="0.1", features=["wasm-bindgen"] }
