[package]
name = "naia-bevy-client"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Library to faciliate naia_client & Bevy interop"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
naia-client = { version = "0.7.0", path = "../../../client", features = ["wbindgen", "mquad","bevy-support"] }
naia-bevy-shared = { version = "0.7.0", path = "../shared"}
bevy = { version="=0.6.0", default-features=false }
