[package]
name = "naia-bevy-shared"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Library to faciliate naia & Bevy interop, functionality shared by client & server versions"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
naia-shared = { version = "0.7.0", path = "../../../shared", features = ["wbindgen"] }
bevy = { version="=0.6.0", default-features=false }